<a href="https://colab.research.google.com/github/Roll1ngo/Authorization_and_authentication_synopsis/blob/master/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Home Work module 1

In [49]:
import numpy as np

In [50]:
np.random.seed(0)

1.Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [51]:
v = np.array([range(0,10)], dtype=int) #  стандарт ISO 80000-2
print(v)

[[0 1 2 3 4 5 6 7 8 9]]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [52]:
mx_zeros_3x3 = np.zeros((3,3),dtype=int)
print(mx_zeros_3x3)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3.Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [53]:
mx_random = np.random.randint(1,11, size=(5,5))
print(mx_random)

[[ 6  1  4  4  8]
 [10  4  6  3  5]
 [ 8  7  9  9  2]
 [ 7  8  8  9  2]
 [ 6 10  9 10  5]]


4.Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [54]:
mx_random = np.random.rand(4,4)
print(mx_random)

[[0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918]
 [0.11827443 0.63992102 0.14335329 0.94466892]
 [0.52184832 0.41466194 0.26455561 0.77423369]]


5.Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [55]:
v_1 = np.random.randint(1,11, size=(5))
v_2 = np.random.randint(1,11, size=(5))
print(f"v1 = {v_1}\nv2 = {v_2}\nadd:{np.add(v_1,v_2)}\nsub: {np.subtract(v_1,v_2)}\nmultiply: {np.multiply(v_1,v_2)} ")

v1 = [8 3 1 1 5]
v2 = [6 6 7 9 5]
add:[14  9  8 10 10]
sub: [ 2 -3 -6 -8  0]
multiply: [48 18  7  9 25] 


or

In [56]:
print(f"v1 = {v_1}\nv2 = {v_2}\nadd:{v_1+v_2}\nsub: {v_1-v_2}\nmultiply: {v_1*v_2} ")

v1 = [8 3 1 1 5]
v2 = [6 6 7 9 5]
add:[14  9  8 10 10]
sub: [ 2 -3 -6 -8  0]
multiply: [48 18  7  9 25] 


6.Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [57]:
v_1 = np.random.randint(1,11, size=(7))
v_2 = np.random.randint(1,11, size=(7))
print(np.multiply(v_1,v_2))

[20 50 40 63 16  6  8]


7.Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

8.Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [58]:
mx = np.random.randint(1,11, size=(3,3))
mx_inv = np.linalg.pinv(mx)
print(f'random matrix 3x3\n{mx}\ninversion matrix\n{mx_inv}')

random matrix 3x3
[[ 4  6 10]
 [ 5  5  7]
 [ 5  5  4]]
inversion matrix
[[-5.00000000e-01  8.66666667e-01 -2.66666667e-01]
 [ 5.00000000e-01 -1.13333333e+00  7.33333333e-01]
 [ 2.07894146e-16  3.33333333e-01 -3.33333333e-01]]


9.Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [59]:
mx = np.random.rand(4,4)

print(f'random matrix 4x4\n{mx}\ntranspose matrix mx.T\n{mx.T}\nor mx.transpose()\n{mx.transpose()}')


random matrix 4x4
[[0.99529957 0.58185033 0.41436859 0.4746975 ]
 [0.6235101  0.33800761 0.67475232 0.31720174]
 [0.77834548 0.94957105 0.66252687 0.01357164]
 [0.6228461  0.67365963 0.971945   0.87819347]]
transpose matrix mx.T
[[0.99529957 0.6235101  0.77834548 0.6228461 ]
 [0.58185033 0.33800761 0.94957105 0.67365963]
 [0.41436859 0.67475232 0.66252687 0.971945  ]
 [0.4746975  0.31720174 0.01357164 0.87819347]]
or mx.transpose()
[[0.99529957 0.6235101  0.77834548 0.6228461 ]
 [0.58185033 0.33800761 0.94957105 0.67365963]
 [0.41436859 0.67475232 0.66252687 0.971945  ]
 [0.4746975  0.31720174 0.01357164 0.87819347]]


10.Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [60]:
mx = np.random.randint(1,11, size=(3,4), dtype=int)
v = np.random.randint(1,11, size=(4))
multiply_mx_v = np.dot(mx,v)
print(f'random matrix 3x4\n{mx}\nrandom vector\n{v}\nmultiply matrix and vector\n{multiply_mx_v}')


random matrix 3x4
[[ 1  8  6 10]
 [ 1  3  8  3]
 [10  3  4  4]]
random vector
[3 4 5 2]
multiply matrix and vector
[85 61 70]


11.Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [61]:
mx = np.random.rand(2,3)
v = np.random.rand(3)
multiply_mx_v = np.dot(mx,v)
print(f'random matrix 2x3\n{mx}\nrandom vector\n{v}\nmultiply matrix and vector\n{multiply_mx_v}')

random matrix 2x3
[[0.50896896 0.91672295 0.92115761]
 [0.08311249 0.27771856 0.0093567 ]]
random vector
[0.84234208 0.64717414 0.84138612]
multiply matrix and vector
[1.79705459 0.25761402]


12.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [62]:
mx_1 = np.random.randint(1,11, size=(2,2))
mx_2 = np.random.randint(1,11, size=(2,2))
print(f'matrix_1:\n{mx_1}\nmatrix_2:\n{mx_2}\nelement-by-element multiplication of matrices mx_1*mx_2:\
\n{mx_1*mx_2}\n or np.multiply(mx_1,mx_2)\n{np.multiply(mx_1,mx_2)}')

matrix_1:
[[7 4]
 [4 9]]
matrix_2:
[[9 9]
 [3 4]]
element-by-element multiplication of matrices mx_1*mx_2:
[[63 36]
 [12 36]]
 or np.multiply(mx_1,mx_2)
[[63 36]
 [12 36]]


13.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [63]:
mx_1 = np.random.randint(1,11, size=(2,2))
mx_2 = np.random.randint(1,11, size=(2,2))
scalar_product = np.sum(np.multiply(mx_1, mx_2))
print(f'matrix_1:\n{mx_1}\nmatrix_2:\n{mx_2}\n scalar_product:\n{scalar_product}')

matrix_1:
[[3 1]
 [9 9]]
matrix_2:
[[4 9]
 [3 9]]
 scalar_product:
129


14.Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [64]:
mx = np.random.randint(1,100, size=(5,5))
print(f'matrix:\n{mx}\n np.sum(matrix)\n{np.sum(mx)}\nor matrix.sum()\n{mx.sum()}')

matrix:
[[53 68 62 15 97]
 [ 5 68 12 87 78]
 [76 57 17 25 30]
 [22 26 81 61 62]
 [84 34 33 71 86]]
 np.sum(matrix)
1310
or matrix.sum()
1310


15.Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [65]:
mx_1 = np.random.randint(1,11, size=(4,4))
mx_2 = np.random.randint(1,11, size=(4,4))
np_matrix_sub = np.subtract(mx_1, mx_2)
py_matrix_sub = mx_1 - mx_2
print(f"np matrixs subtract:\n{np_matrix_sub}\npython matrixs subtract\n{py_matrix_sub}")

np matrixs subtract:
[[ 1  5  2  4]
 [-5  8 -2  2]
 [ 3 -4 -2  6]
 [ 5 -6 -5 -2]]
python matrixs subtract
[[ 1  5  2  4]
 [-5  8 -2  2]
 [ 3 -4 -2  6]
 [ 5 -6 -5 -2]]


16.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [66]:
mx = np.random.rand(3,3)
v = np.sum(mx, axis=0)

print(f'random matrix 3x3\n{mx}\nnp.sum(matrix, axis=0)\n{v}')

random matrix 3x3
[[0.84800823 0.80731896 0.56910074]
 [0.4071833  0.069167   0.69742877]
 [0.45354268 0.7220556  0.86638233]]
np.sum(matrix, axis=0)
[1.70873421 1.59854155 2.13291184]


17.Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [67]:
mx = np.random.randint(1,11, size=(3,4))
print(f'Python make square elements: matrix**2\n{mx**2}\n\
 Numpy make square elements np.square(matrix)\n{np.square(mx)}')

Python make square elements: matrix**2
[[100  64  64  36]
 [  4   9   9  81]
 [  4  36  81  25]]
 Numpy make square elements np.square(matrix)
[[100  64  64  36]
 [  4   9   9  81]
 [  4  36  81  25]]


18.Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [68]:
v = np.random.randint(1,50, size=(4))
print(f'Python make square elements: vector**2\n{v**2}\n\
 Numpy make square elements np.square(vector)\n{np.square(v)}')

Python make square elements: vector**2
[   1  144 1225   36]
 Numpy make square elements np.square(vector)
[   1  144 1225   36]
