<a href="https://colab.research.google.com/github/Roll1ngo/Authorization_and_authentication_synopsis/blob/master/lecture1_linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Operations with vectors

In [ ]:
import numpy as np


In [ ]:
a=[3,5,5,6,6]
b=[5,1,6,8,3]

In [ ]:
a=np.array(a)
b=np.array(b)

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.size

5

In [ ]:
a+3

array([6, 8, 8, 9, 9])

In [ ]:
b-1

array([4, 0, 5, 7, 2])

In [ ]:
print(b)
c=b*2
print(c)
print(type(c))

[5 1 6 8 3]
[10  2 12 16  6]
<class 'numpy.ndarray'>


In [ ]:
a*0

array([0, 0, 0, 0, 0])

In [ ]:
print(a)
print(b)
print(a+b)
print(a*b)

[3 5 5 6 6]
[5 1 6 8 3]
[ 8  6 11 14  9]
[15  5 30 48 18]


Добуток двох векторів

In [ ]:
print(a)
print(b)
print(a*b)

[3 5 5 6 6]
[5 1 6 8 3]
[15  5 30 48 18]


Добуток векторів в numpy

In [ ]:
print(a)
print(b)
d=np.dot(a,b)
c=sum(a*b)
print(type(d))
print(type(c))


[3 5 5 6 6]
[5 1 6 8 3]
<class 'numpy.int64'>
<class 'numpy.int64'>


Матриці

In [ ]:
matrix = np.array([
    [4,5,6,7,1],
    [1,6,5,3,2],
    [9,5,4,1,3],
    [3,6,3,7,1]])

In [ ]:
matrix

array([[4, 5, 6, 7, 1],
       [1, 6, 5, 3, 2],
       [9, 5, 4, 1, 3],
       [3, 6, 3, 7, 1]])